version: '2'
services:
  mysql:
    image: mysql/mysql-server:8.0.20
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recordings
      MYSQL_USER: test
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
